"""
====================================================================
Institutional Quant Platform

Fill Event

Author : Institutional Quant Platform

Purpose
-------
Represents the completion (full or partial)
of an order execution.

Generated By

• Execution Engine
• Broker
• Broker Simulator

Consumed By

• Portfolio Tracker
• Cash Manager
• Performance Engine
• Position Manager

Inherited From

• Event

====================================================================
"""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from datetime import datetime

from backtesting.event import Event


@dataclass(slots=True)
class FillEvent(Event):
    """
    Institutional fill event.
    """

    order_id: str = ""

    symbol: str = ""

    side: str = ""

    executed_quantity: float = 0.0

    remaining_quantity: float = 0.0

    execution_price: float = 0.0

    commission: float = 0.0

    slippage: float = 0.0

    market_impact: float = 0.0

    broker: str = ""

    venue: str = ""

    timestamp: datetime = field(

        default_factory=datetime.utcnow

    )

    metadata: dict = field(

        default_factory=dict

    )

    __hash__ = None

    # =====================================================
    # EVENT TYPE
    # =====================================================

    @property
    def event_type(

        self,

    ) -> str:

        return "FILL"

    # =====================================================
    # VALIDATION
    # =====================================================

    def __post_init__(

        self,

    ) -> None:

        if not self.order_id:

            raise ValueError(

                "Order ID cannot be empty."

            )

        if not self.symbol:

            raise ValueError(

                "Symbol cannot be empty."

            )

        self.side = self.side.upper()

        if self.side not in {

            "BUY",

            "SELL",

        }:

            raise ValueError(

                "Side must be BUY or SELL."

            )

        if self.executed_quantity < 0:

            raise ValueError(

                "Executed quantity cannot be negative."

            )

    # =====================================================
    # PROPERTIES
    # =====================================================

    @property
    def execution_value(

        self,

    ) -> float:

        return (

            self.executed_quantity

            *

            self.execution_price

        )

    @property
    def total_cost(

        self,

    ) -> float:

        return (

            self.commission

            +

            self.slippage

            +

            self.market_impact

        )

    @property
    def net_execution_value(

        self,

    ) -> float:

        return (

            self.execution_value

            +

            self.total_cost

            if self.side == "BUY"

            else

            self.execution_value

            -

            self.total_cost

        )

    @property
    def is_complete(

        self,

    ) -> bool:

        return (

            self.remaining_quantity

            <= 0.0

        )

    # =====================================================
    # EXPORT
    # =====================================================

    def to_dict(

        self,

    ) -> dict:

        return {

            "Event":

                self.event_type,

            "Timestamp":

                self.timestamp.isoformat(),

            "OrderID":

                self.order_id,

            "Symbol":

                self.symbol,

            "Side":

                self.side,

            "ExecutedQuantity":

                self.executed_quantity,

            "RemainingQuantity":

                self.remaining_quantity,

            "ExecutionPrice":

                self.execution_price,

            "ExecutionValue":

                self.execution_value,

            "Commission":

                self.commission,

            "Slippage":

                self.slippage,

            "MarketImpact":

                self.market_impact,

            "TotalCost":

                self.total_cost,

            "Broker":

                self.broker,

            "Venue":

                self.venue,

            "Metadata":

                self.metadata,

        }

    # =====================================================
    # SUMMARY
    # =====================================================

    def summary(

        self,

    ) -> dict:

        return {

            "Order":

                self.order_id,

            "Symbol":

                self.symbol,

            "Side":

                self.side,

            "Executed":

                self.executed_quantity,

            "Price":

                self.execution_price,

            "Value":

                self.execution_value,

            "Cost":

                self.total_cost,

            "Broker":

                self.broker,

        }

    # =====================================================
    # REPRESENTATION
    # =====================================================

    def __repr__(

        self,

    ) -> str:

        return (

            f"{self.__class__.__name__}("

            f"{self.symbol}, "

            f"{self.executed_quantity:.2f} @ "

            f"{self.execution_price:.2f}"

            f")"

        )

    __str__ = __repr__