"""
====================================================================
Institutional Quant Platform

Market Event

Author : Institutional Quant Platform

Purpose
-------
Represents the arrival of new market data.

Generated By

• Market Data Feed
• Historical Data Loader
• Live Data Feed

Consumed By

• EventEngine
• Signal Engine
• Portfolio Manager
• Risk Engine

Inherited From

• Event

====================================================================
"""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from datetime import datetime

from backtesting.event import Event


@dataclass(slots=True)
class MarketEvent(Event):
    """
    Institutional market event.
    """

    symbol: str = ""

    timestamp: datetime = field(

        default_factory=datetime.utcnow

    )

    open: float = 0.0

    high: float = 0.0

    low: float = 0.0

    close: float = 0.0

    volume: float = 0.0

    adjusted_close: float = 0.0

    metadata: dict = field(

        default_factory=dict

    )

    __hash__ = None

    # =====================================================
    # EVENT TYPE
    # =====================================================

    @property
    def event_type(

        self,

    ) -> str:

        return "MARKET"

    # =====================================================
    # VALIDATION
    # =====================================================

    def __post_init__(

        self,

    ) -> None:

        if not self.symbol:

            raise ValueError(

                "Symbol cannot be empty."

            )

        if self.high < self.low:

            raise ValueError(

                "High cannot be less than Low."

            )

        if self.volume < 0:

            raise ValueError(

                "Volume cannot be negative."

            )

        if self.adjusted_close == 0.0:

            self.adjusted_close = self.close

    # =====================================================
    # OHLC
    # =====================================================

    @property
    def ohlc(

        self,

    ) -> tuple[float, float, float, float]:

        return (

            self.open,

            self.high,

            self.low,

            self.close,

        )

    # =====================================================
    # TYPICAL PRICE
    # =====================================================

    @property
    def typical_price(

        self,

    ) -> float:

        return (

            self.high

            +

            self.low

            +

            self.close

        ) / 3.0

    # =====================================================
    # EXPORT
    # =====================================================

    def to_dict(

        self,

    ) -> dict:

        return {

            "Event":

                self.event_type,

            "Symbol":

                self.symbol,

            "Timestamp":

                self.timestamp.isoformat(),

            "Open":

                self.open,

            "High":

                self.high,

            "Low":

                self.low,

            "Close":

                self.close,

            "AdjustedClose":

                self.adjusted_close,

            "Volume":

                self.volume,

            "Metadata":

                self.metadata,

        }

    # =====================================================
    # SUMMARY
    # =====================================================

    def summary(

        self,

    ) -> dict:

        return {

            "Symbol":

                self.symbol,

            "Close":

                self.close,

            "Volume":

                self.volume,

            "Timestamp":

                self.timestamp,

        }

    # =====================================================
    # REPRESENTATION
    # =====================================================

    def __repr__(

        self,

    ) -> str:

        return (

            f"{self.__class__.__name__}("

            f"{self.symbol}, "

            f"Close={self.close:.2f}"

            f")"

        )

    __str__ = __repr__