"""
====================================================================
Institutional Quant Platform

Order Event

Author : Institutional Quant Platform

Purpose
-------
Represents an order generated from a
trading signal.

Generated By

• Portfolio Manager
• Optimizer
• Signal Engine

Consumed By

• Execution Engine
• Broker
• Order Router

Inherited From

• Event

====================================================================
"""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from datetime import datetime

from backtesting.event import Event


@dataclass(slots=True)
class OrderEvent(Event):
    """
    Institutional order event.
    """

    order_id: str = ""

    symbol: str = ""

    side: str = ""

    quantity: float = 0.0

    order_type: str = "MARKET"

    price: float | None = None

    timestamp: datetime = field(

        default_factory=datetime.utcnow

    )

    metadata: dict = field(

        default_factory=dict

    )

    __hash__ = None

    # =====================================================
    # EVENT TYPE
    # =====================================================

    @property
    def event_type(

        self,

    ) -> str:

        return "ORDER"

    # =====================================================
    # VALIDATION
    # =====================================================

    def __post_init__(

        self,

    ) -> None:

        if not self.order_id:

            raise ValueError(

                "Order ID cannot be empty."

            )

        if not self.symbol:

            raise ValueError(

                "Symbol cannot be empty."

            )

        self.side = self.side.upper()

        if self.side not in {

            "BUY",

            "SELL",

        }:

            raise ValueError(

                "Side must be BUY or SELL."

            )

        self.order_type = (

            self.order_type

            .upper()

        )

        if self.quantity <= 0:

            raise ValueError(

                "Quantity must be positive."

            )

    # =====================================================
    # PROPERTIES
    # =====================================================

    @property
    def is_buy(

        self,

    ) -> bool:

        return self.side == "BUY"

    @property
    def is_sell(

        self,

    ) -> bool:

        return self.side == "SELL"

    @property
    def notional(

        self,

    ) -> float:

        if self.price is None:

            return 0.0

        return (

            self.quantity

            *

            self.price

        )

    # =====================================================
    # EXPORT
    # =====================================================

    def to_dict(

        self,

    ) -> dict:

        return {

            "Event":

                self.event_type,

            "Timestamp":

                self.timestamp.isoformat(),

            "OrderID":

                self.order_id,

            "Symbol":

                self.symbol,

            "Side":

                self.side,

            "Quantity":

                self.quantity,

            "OrderType":

                self.order_type,

            "Price":

                self.price,

            "Notional":

                self.notional,

            "Metadata":

                self.metadata,

        }

    # =====================================================
    # SUMMARY
    # =====================================================

    def summary(

        self,

    ) -> dict:

        return {

            "Order":

                self.order_id,

            "Symbol":

                self.symbol,

            "Side":

                self.side,

            "Quantity":

                self.quantity,

            "Type":

                self.order_type,

            "Notional":

                self.notional,

        }

    # =====================================================
    # REPRESENTATION
    # =====================================================

    def __repr__(

        self,

    ) -> str:

        return (

            f"{self.__class__.__name__}("

            f"{self.side} "

            f"{self.quantity:.2f} "

            f"{self.symbol}"

            f")"

        )

    __str__ = __repr__