"""
====================================================================
Institutional Quant Platform

Signal Event

Author : Institutional Quant Platform

Purpose
-------
Represents a trading signal generated by
an alpha model or strategy.

Generated By

• Alpha Engine
• Factor Models
• Signal Engine
• Machine Learning Models

Consumed By

• EventEngine
• Portfolio Optimizer
• Order Generator
• Risk Engine

Inherited From

• Event

====================================================================
"""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from datetime import datetime

from backtesting.event import Event


@dataclass(slots=True)
class SignalEvent(Event):
    """
    Institutional signal event.
    """

    symbol: str = ""

    signal: str = ""

    confidence: float = 1.0

    expected_return: float = 0.0

    target_weight: float = 0.0

    timestamp: datetime = field(

        default_factory=datetime.utcnow

    )

    metadata: dict = field(

        default_factory=dict

    )

    __hash__ = None

    # =====================================================
    # EVENT TYPE
    # =====================================================

    @property
    def event_type(

        self,

    ) -> str:

        return "SIGNAL"

    # =====================================================
    # VALIDATION
    # =====================================================

    def __post_init__(

        self,

    ) -> None:

        if not self.symbol:

            raise ValueError(

                "Symbol cannot be empty."

            )

        self.signal = (

            self.signal

            .upper()

        )

        if self.signal not in {

            "BUY",

            "SELL",

            "HOLD",

        }:

            raise ValueError(

                "Signal must be BUY, SELL or HOLD."

            )

        if not (

            0.0

            <=

            self.confidence

            <=

            1.0

        ):

            raise ValueError(

                "Confidence must be between 0 and 1."

            )

    # =====================================================
    # PROPERTIES
    # =====================================================

    @property
    def is_buy(

        self,

    ) -> bool:

        return self.signal == "BUY"

    @property
    def is_sell(

        self,

    ) -> bool:

        return self.signal == "SELL"

    @property
    def is_hold(

        self,

    ) -> bool:

        return self.signal == "HOLD"

    # =====================================================
    # EXPORT
    # =====================================================

    def to_dict(

        self,

    ) -> dict:

        return {

            "Event":

                self.event_type,

            "Timestamp":

                self.timestamp.isoformat(),

            "Symbol":

                self.symbol,

            "Signal":

                self.signal,

            "Confidence":

                self.confidence,

            "Expected_Return":

                self.expected_return,

            "Target_Weight":

                self.target_weight,

            "Metadata":

                self.metadata,

        }

    # =====================================================
    # SUMMARY
    # =====================================================

    def summary(

        self,

    ) -> dict:

        return {

            "Symbol":

                self.symbol,

            "Signal":

                self.signal,

            "Confidence":

                self.confidence,

            "Expected Return":

                self.expected_return,

            "Target Weight":

                self.target_weight,

        }

    # =====================================================
    # REPRESENTATION
    # =====================================================

    def __repr__(

        self,

    ) -> str:

        return (

            f"{self.__class__.__name__}("

            f"{self.symbol}, "

            f"{self.signal}, "

            f"{self.confidence:.0%}"

            f")"

        )

    __str__ = __repr__