extends: default

ignore: |
  rendered.yaml
  docs/infrastructure/helm/templates/**

rules:
  document-start: disable

  line-length:
    max: 120
    level: warning

  comments-indentation: disable

  indentation:
    spaces: 2
    indent-sequences: true

  truthy: disable